project:
  type: book

book:
  title: 'Una prueba transicional de la confluencia de la reducción $\eta$'
  author:
    - name: "Maximiliano Onofre Martínez"
  chapters:
    - index.qmd
    - Capitulo1.qmd
    - Capitulo2.qmd
    - Capitulo3.qmd
    - Capitulo4.qmd
lang: es
format:
  pdf:
    pdf-engine: xelatex
    documentclass: scrreprt
    toc-depth: 2
    number-depth: 0
    syntax-definitions: [lean.xml]
    include-in-header: inpreamble.tex
    monofont: JuliaMono
    keep-tex: true
