# Relaciones

## 1.1. Definiciones básicas

::: {.ndfn arguments="Definición 1.1.1"}
Una relación binaria sobre un tipo `α` es una función `α → α → Prop`,
es decir, una proposición sobre pares de elementos de `α`.
:::
 
```lean
variable {α : Type} {r : α → α → Prop}
```

::: {.ndfn arguments="Definición 1.1.2"}
Sea `r` una relación en `α`.
Entonces `r` induce las siguientes relaciones binarias.

I\. `ReflGen r` es la cerradura reflexiva de `r`, 
definida inductivamente de la siguiente manera:

```lean
inductive ReflGen {α : Type} (r : α → α → Prop) : α → α → Prop
  | refl {a : α}: ReflGen r a a
  | single {a b : α} : r a b → ReflGen r a b
```

II\. `ReflTransGen r` es la cerradura reflexiva y transitiva de `r`,
definida inductivamente de la siguiente manera:

```lean
inductive ReflTransGen {α : Type} (r : α → α → Prop) : α → α → Prop
  | refl {a : α} : ReflTransGen r a a
  | tail {a b c : α} : ReflTransGen r a b → r b c → ReflTransGen r a c
```
:::

::: {.nthm arguments="Teorema 1.1.1"}
Si dos términos están relacionados por la cerradura reflexiva de `r`, 
entonces también lo están por su cerradura reflexiva y transitiva.
```lean
theorem ReflGen.to_reflTransGen :
  ∀ {a b : α}, ReflGen r a b → ReflTransGen r a b
```
:::

Las relaciones anteriores pueden describirse mediante caminos de `a` a `b`:

- `r a b` indica la existencia de un camino de longitud 1. 
- `ReflGen r a b`, de un camino de longitud 0 o 1. 
- `ReflTransGen r a b`, de un camino de longitud $n$, para algún $n \in \mathbb{N}$.

Representamos estas relaciones mediante 
`a` $\to$ `b`, `a` $\to^{=}$ `b` y `a` $\twoheadrightarrow$ `b`, respectivamente.


::: {.ndfn arguments="Definición 1.1.3"}
Sea `r` una relación en `α`. 

Decimos que `r` tiene la _propiedad del diamante_
si, para cualesquiera `a`, `b` y `c` tales que `a` $\to$ `b` y `a` $\to$ `c`,
existe un elemento `d` tal que `b` $\to$ `d` y `c` $\to$ `d`. 
Visualmente, esta propiedad afirma que el siguiente diagrama siempre puede completarse:

```{=latex}
\begin{center}
\begin{tikzpicture}
  \node (a) at (0, 2) {\lean{a}};
  \node (b) at (2, 2) {\lean{b}};
  \node (c) at (0, 0) {\lean{c}};
  \node (d) at (2, 0) {\lean{d}};
  \draw[->]           (a) -- node[above] {\lean{r}} (b);
  \draw[->]           (a) -- node[left]  {\lean{r}} (c);
  \draw[->, dashed] (b) -- node[right] {\lean{r}} (d);
  \draw[->, dashed] (c) -- node[below] {\lean{r}} (d);
\end{tikzpicture}
\end{center}
```

```lean
def Diamond (r : α → α → Prop) :=
  ∀ {a b c : α}, r a b → r a c → ∃ d, r b d ∧ r c d
```
:::

### Confluencia y Conmutación

::: {.ndfn arguments="Definición 1.1.4"}
Sea `r` una relación en `α`.

I\. `r` es **confluente** si su cerradura 
reflexiva y transitiva tiene la propiedad del diamante.

```{=latex}
\begin{center}
\begin{tikzpicture}
  \node (a) at (0, 2) {\lean{a}};
  \node (b) at (2, 2) {\lean{b}};
  \node (c) at (0, 0) {\lean{c}};
  \node (d) at (2, 0) {\lean{d}};
  \draw[->>]           (a) -- node[above] {\lean{r}} (b);
  \draw[->>]           (a) -- node[left]  {\lean{r}} (c);
  \draw[->>, dashed] (b) -- node[right] {\lean{r}} (d);
  \draw[->>, dashed] (c) -- node[below] {\lean{r}} (d);
\end{tikzpicture}
\end{center}
```

```lean
def Confluent (r : α → α → Prop) := Diamond (ReflTransGen r)
```

II\. `r` es **fuertemente confluente** si:

```{=latex}
\begin{center}
\begin{tikzpicture}
  \node (a) at (0, 2) {\lean{x}};
  \node (b) at (2, 2) {\lean{y₁}};
  \node (c) at (0, 0) {\lean{y₂}};
  \node (d) at (2, 0) {\lean{z}};
  \draw[->]         (a) -- node[above] {\lean{r}} (b);
  \draw[->]         (a) -- node[left]  {\lean{r}} (c);
  \draw[->, dashed] (b) -- node[right] {\lean{r}} node[left] {$=$} (d);
  \draw[->>, dashed] (c) -- node[below] {\lean{r}} (d);
\end{tikzpicture}
\end{center}
```

```lean
def StronglyConfluent (r : α → α → Prop) :=
  ∀ {x y₁ y₂}, r x y₁ → r x y₂ → ∃ z, ReflGen r y₁ z ∧ ReflTransGen r y₂ z
```
:::

::: {.nthm arguments="Teorema 1.1.2"}
Si una relación es fuertemente confluente, entonces también es confluente.
```lean
theorem StronglyConfluent.toConfluent (h : StronglyConfluent r) : Confluent r 
```
:::

::: {.ndfn arguments="Definición 1.1.5"}
Sean `r₁` y `r₂` dos relaciones en `α`.

I\. `r₁` y `r₂` **conmutan** si:

```{=latex}
\begin{center}
\begin{tikzpicture}
  \node (A) at (0, 2) {\lean{x}};
  \node (B) at (2, 2) {\lean{y₁}};
  \node (C) at (0, 0) {\lean{y₂}};
  \node (D) at (2, 0) {\lean{z}};
  \draw[->>]         (A) -- node[above] {\lean{r₁}} (B);
  \draw[->>]         (A) -- node[left]  {\lean{r₂}} (C);
  \draw[->>, dashed] (B) -- node[right] {\lean{r₂}} (D);
  \draw[->>, dashed] (C) -- node[below] {\lean{r₁}} (D);
\end{tikzpicture}
\end{center}
```

```lean
def Commute (r₁ r₂ : α → α → Prop) :=
  ∀ {x y₁ y₂}, ReflTransGen r₁ x y₁ → ReflTransGen r₂ x y₂ → 
    ∃ z, ReflTransGen r₂ y₁ z ∧ ReflTransGen r₁ y₂ z
```


II\. `r₁` y `r₂` **conmutan fuertemente** si:

```{=latex}
\begin{center}
\begin{tikzpicture}
  \node (A) at (0, 2) {\lean{x}};
  \node (B) at (2, 2) {\lean{y₁}};
  \node (C) at (0, 0) {\lean{y₂}};
  \node (D) at (2, 0) {\lean{z}};
  \draw[->] (A) -- node[above] {\lean{r₁}}  (B);
  \draw[->] (A) -- node[left] {\lean{r₂}} (C);
  \draw[->, dashed] (B)-- node[right] {\lean{r₂}} node[left] {$=$} (D);
  \draw[->>, dashed] (C)-- node[below]  {\lean{r₁}}  (D);
\end{tikzpicture}
\end{center}
```

```lean
def StronglyCommute (r₁ r₂ : α → α → Prop) :=
  ∀ {x y₁ y₂}, r₁ x y₁ → r₂ x y₂ → ∃ z, ReflGen r₂ y₁ z ∧ ReflTransGen r₁ y₂ z
```
::: 

::: {.nthm arguments="Teorema 1.1.3"}
Si dos relaciones conmutan fuertemente, entonces también conmutan.
```lean
theorem StronglyCommute.toCommute {r₁ r₂ : α → α → Prop} 
  (h : StronglyCommute r₁ r₂) : Commute r₁ r₂ 
```
:::

::: {.nthm arguments="Teorema 1.1.4"}
La conmutación entre relaciones es simétrica, es decir, 
si `r₁` y `r₂` conmutan, 
entonces `r₂` y `r₁` también.
```lean
theorem Commute.symmetric : Symmetric (@Commute α)
```
:::

::: {.nthm arguments="Teorema 1.1.5 (Hindley-Rosen)"}
Sean `r₁` y `r₂` dos relaciones sobre un mismo tipo. Si ambas son
confluentes y conmutan entre sí, entonces su unión `r₁ ⊔ r₂` es
confluente.
```lean
theorem Commute.join_confluent {r₁ r₂ : α → α → Prop}
  (c₁ : Confluent r₁) (c₂ : Confluent r₂) (comm : Commute r₁ r₂) : 
    Confluent (r₁ ⊔ r₂)
```
:::
